common: &common
  adapter: postgresql
  encoding: utf8
  template: template1
  username: city_dashboard
  password: city_dashboard
  pool: 15

development:
  <<: *common
  database: city_dashboard_development

test:
  <<: *common
  database: city_dashboard_test

production:
  <<: *common
  database: city_dashboard_production